# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100', '0002_auto_20160823_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 9, 20)),
        ),
    ]
