# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100', '0003_auto_20160920_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='media',
        ),
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 9, 27)),
        ),
    ]
