# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100', '0004_auto_20160927_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='libuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='libitem',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
    ]
