# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test100', '0005_auto_20160927_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
